# The main config file for your Jekyll template

# Site settings
title: Jennifer Campbell               # used for the html title of every page
desc: Jennifer Campbell, Associate Professor, Teaching Stream    # comment

url: http://www.cs.toronto.edu/~campbell      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: campbell@cs.toronto.edu
author: ''
twitter_username: jencampbellTO
github_username: jencampbell
#github_source: 

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: About
    url: /index/
    desc: About me
  - title: Teaching
    url: /teaching/
    desc: My courses
  - title: Publications
    url: /publications/
    desc: My publications
  - title: Contact
    url: /contact/
    desc: Contact me

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

